const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
const GET_ALL_FRAGANCES = 'GET_ALL_FRAGANCES'
const ORDER_NAME = 'ORDER_NAME'
const ORDER_PRICE = 'ORDER_PRICE'
const FILTER_GENDER = 'FILTER_GENDER'
const SEARCH_BY_NAME = 'SEARCH_BY_NAME'
const FILTER_FRAGANCE = 'FILTER_FRAGANCE'
const COMBINATED_FILTER = 'COMBINATED_FILTER'

export {
    GET_PRODUCTS,
    GET_PRODUCT_BY_ID,
    GET_ALL_FRAGANCES,
    ORDER_NAME,
    ORDER_PRICE,
    FILTER_GENDER,
    SEARCH_BY_NAME,
    FILTER_FRAGANCE,
    COMBINATED_FILTER,
}